language: csharp
solution: LibraryApp.sln
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/master/kvminstall.sh | sh && source ~/.k/kvm/kvm.sh
  - kvm upgrade
  - kpm restore --no-cache
script:
  - k test -parallel none
<<<<<<< HEAD

notifications:
  email:
    recipients:
      - mah9@tpu.ru
      - markoosha98@gmail.com
    on_success: change
    on_failure: always
=======
>>>>>>> 0573026b0eece5361aed5f285b4751b15b8327c6
