language: csharp
solution: LibraryApp.sln
install:
  - nuget restore LibraryApp.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release LibraryApp.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./LibraryApp.Tests/bin/Debug/LibraryApp.Tests.dll
