language: csharp
solution: LibraryApp.sln
mono: none
dotnet: 2.1.502
script:
 - dotnet restore
<<<<<<< HEAD

notifications:
  email:
    recipients:
      - mah9@tpu.ru
      - markoosha98@gmail.com
    on_success: changes
    on_failure: always
=======
>>>>>>> 0573026b0eece5361aed5f285b4751b15b8327c6
