language: csharp
solution: LibraryApp.sln
mono: latest
dotnet: 3.1.200
before_install:
  - cd src
script:
  - dotnet restore
  - msbuild
  - dotnet test LibraryApp.Tests/Controllers/HomeControllerTest.cs
<<<<<<< HEAD

notifications:
  email:
    recipients:
      - mah9@tpu.ru
      - markoosha98@gmail.com
    on_success: changes
    on_failure: always
=======
>>>>>>> 0573026b0eece5361aed5f285b4751b15b8327c6
